### PR TITLE
Update credits to reflect reality!

### PR DESCRIPTION
**Pull request by jhalt**

### CODE REVIEW

**Comment by ShonP40** [comment]
Ok, I updated it.
I didn't think that you'll even come here.

**Comment by jhalt** [comment]
Thanks! Credits LGTM!

**Comment by ShonP40** [comment]
:thumbsup:

**Comment by ShonP40** [comment]
Can you add me on Discord (ShonP40#7172)? I want to ask you something about CheatBreaker.

**Pull request closed without merging**
